
stages:
    - test
    - deploy
before_script:
  - export PATH=$PATH:/home/gitlab-runner/.nvm/versions/node/v14.20.1/bin
  - export NVM_DIR="$HOME/.nvm"
#image: ubuntu
#before_script:
#    - apt-get update -qq
#    - apt-get install -qq git curl
#    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
#    - eval $(ssh-agent -s)
#    - ssh-add <(echo "$SSH_PRIVATE_KEY")
#    - mkdir -p ~/.ssh
#    - chmod 700 ~/.ssh
#    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
#    - git config --global user.email "olef_and@ukr.net"
#    - git config --global user.name "andrii"
  
#test_package:
#    stage: test
#    script:
#      - >-
#        echo "nice"

update_master:
    stage: deploy
    script:
      - >-
        source ~/.bashrc
        && echo $PATH
        && ls -lahs $HOME/
        && pwd
        && cd $HOME/dom-pwa/
        && GIT_SSH_COMMAND='ssh -i /home/gitlab-runner/.ssh/gitlab_rsa' git pull
        && whoami
        && pwd
        && nvm
        && yarn
        && yarn build
        && exit
      
    only:
      - main